/* code generated by beremiz OPC-UA extension */

#include <open62541/client_config_default.h>
#include <open62541/client_highlevel.h>
#include <open62541/plugin/log_stdout.h>
#include <open62541/plugin/securitypolicy.h>
#include <open62541/plugin/securitypolicy_default.h>

#include <open62541/types.h>
#include <open62541/types_generated_handling.h>

#include <stdint.h>
#include <unistd.h>
#include <pthread.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>

#define _Log(level, ...)                                                                           \
    {{                                                                                             \
        char mstr[256];                                                                            \
        snprintf(mstr, 255, __VA_ARGS__);                                                          \
        LogMessage(level, mstr, strlen(mstr));                                                     \
    }}

#define LogInfo(...) _Log(LOG_INFO, __VA_ARGS__);
#define LogError(...) _Log(LOG_CRITICAL, __VA_ARGS__);
#define LogWarning(...) _Log(LOG_WARNING, __VA_ARGS__);

static UA_INLINE UA_ByteString
loadFile(const char *const path) {{
    UA_ByteString fileContents = UA_STRING_NULL;

    FILE *fp = fopen(path, "rb");
    if(!fp) {{
        errno = 0;
        LogError("OPC-UA could not open %s", path);
        return fileContents;
    }}

    fseek(fp, 0, SEEK_END);
    fileContents.length = (size_t)ftell(fp);
    fileContents.data = (UA_Byte *)UA_malloc(fileContents.length * sizeof(UA_Byte));
    if(fileContents.data) {{
        fseek(fp, 0, SEEK_SET);
        size_t read = fread(fileContents.data, sizeof(UA_Byte), fileContents.length, fp);
        if(read != fileContents.length){{
            UA_ByteString_clear(&fileContents);
            LogError("OPC-UA could not read %s", path);
        }}
    }} else {{
        fileContents.length = 0;
        LogError("OPC-UA Not enough memoty to load %s", path);
    }}
    fclose(fp);

    return fileContents;
}}

/* OPCUA client */
static UA_Client *client;
static UA_ClientConfig *cc;

#define DECL_VAR(iec_type, C_type, c_loc_name)                                                     \
static UA_Variant c_loc_name##_variant;                                                                 \
static C_type c_loc_name##_buf = 0;                                                             \
C_type *c_loc_name = &c_loc_name##_buf;

{decl}

/* URI of OPCUA, used by the background thread to connect and retry */
static char *OPCUA_uri;

/* condition to quit connection thread */
static int OPCUA_stop_thread = 0;

/* Keep track of connection state */
static volatile int OPCUA_is_disconnected = 1;

/* mutex to protect client operations */
static pthread_mutex_t OPCUA_client_mutex = PTHREAD_MUTEX_INITIALIZER;

/* wakeup connection thread */
static pthread_cond_t OPCUA_thread_wakeup = PTHREAD_COND_INITIALIZER;

/* thread that handles connection and reconnection */
static pthread_t OPCUA_thread;

void __cleanup_{locstr}(void)
{{
    /* stop connection thread */
    OPCUA_stop_thread = 1;
    if (pthread_mutex_lock(&OPCUA_client_mutex) == 0){{
        /* unblock connection thread so that it can stop normally */
        pthread_cond_signal(&OPCUA_thread_wakeup);
        pthread_mutex_unlock(&OPCUA_client_mutex);
    }}
    /* Wait for thread to finish */
    pthread_join(OPCUA_thread, NULL);
    /* Cleanup client */
    if (client) {{
        UA_Client_disconnect(client);
        UA_Client_delete(client);
    }}
}}

#define INIT_NoAuth()                                                                              \
    LogInfo("OPC-UA Init no auth");                                                                \
    UA_ClientConfig_setDefault(cc);                                                                \
    OPCUA_stop_thread = 0;                                                                         \
    int rc = pthread_create(&OPCUA_thread, NULL, __OPCUA_thread_proc, NULL);                      \
    if (rc != 0) {{                                                                                \
        LogError("OPC-UA Failed to create thread: %d", rc);                                        \
        UA_Client_delete(client);                                                                  \
    }}

/* Note : Single policy is enforced here, by default open62541 client supports all policies */
#define INIT_x509(Policy, UpperCaseMode, PrivateKey, Certificate)                                  \
    LogInfo("OPC-UA Init x509 %s,%s,%s,%s", #Policy, #UpperCaseMode, PrivateKey, Certificate);     \
                                                                                                   \
    UA_ByteString certificate = loadFile(Certificate);                                             \
    UA_ByteString privateKey  = loadFile(PrivateKey);                                              \
                                                                                                   \
    cc->securityMode = UA_MESSAGESECURITYMODE_##UpperCaseMode;                                     \
                                                                                                   \
    /* replacement for default behaviour */                                                        \
    /* UA_ClientConfig_setDefaultEncryption(cc, certificate, privateKey, NULL, 0, NULL, 0); */     \
    do{{                                                                                           \
        UA_StatusCode initRetval = UA_ClientConfig_setDefault(cc);                                 \
        if(initRetval != UA_STATUSCODE_GOOD) {{                                                    \
            retval = initRetval;                                                                   \
            break;                                                                                 \
        }}                                                                                         \
                                                                                                   \
        UA_SecurityPolicy *sp = (UA_SecurityPolicy*)                                               \
            UA_realloc(cc->securityPolicies, sizeof(UA_SecurityPolicy) * 2);                       \
        if(!sp){{                                                                                  \
            retval = UA_STATUSCODE_BADOUTOFMEMORY;                                                 \
            break;                                                                                 \
        }}                                                                                         \
        cc->securityPolicies = sp;                                                                 \
                                                                                                   \
        UA_StatusCode spRetval = UA_SecurityPolicy_##Policy(&cc->securityPolicies[cc->securityPoliciesSize],       \
                                                 certificate, privateKey, &cc->logger);            \
        if(spRetval != UA_STATUSCODE_GOOD) {{                                                      \
            UA_LOG_WARNING(&cc->logger, UA_LOGCATEGORY_USERLAND,                                   \
                           "Could not add SecurityPolicy Policy with error code %s",               \
                           UA_StatusCode_name(spRetval));                                          \
            UA_free(cc->securityPolicies);                                                         \
            cc->securityPolicies = NULL;                                                           \
            retval = spRetval;                                                                     \
            break;                                                                                 \
        }}                                                                                         \
                                                                                                   \
        ++cc->securityPoliciesSize;                                                                \
        retval = UA_STATUSCODE_GOOD;                                                               \
    }} while(0);                                                                                   \
                                                                                                   \
    if(retval == UA_STATUSCODE_GOOD) {{                                                            \
        OPCUA_stop_thread = 0;                                                                     \
        int rc = pthread_create(&OPCUA_thread, NULL, __OPCUA_thread_proc, NULL);                  \
        if (rc != 0) {{                                                                            \
            LogError("OPC-UA Failed to create thread: %d", rc);                                    \
            UA_Client_delete(client);                                                              \
        }}                                                                                          \
    }}                                                                                              \
                                                                                                   \
    UA_ByteString_clear(&certificate);                                                             \
    UA_ByteString_clear(&privateKey);

#define INIT_UserPassword(User, Password)                                                          \
    LogInfo("OPC-UA Init UserPassword %s,%s", User, Password);                                     \
    UA_ClientConfig_setDefault(cc);                                                                \
    retval = UA_Client_connectUsername(client, uri, User, Password);

#define INIT_READ_VARIANT(ua_type, c_loc_name)                                                     \
    UA_Variant_init(&c_loc_name##_variant);

#define INIT_WRITE_VARIANT(ua_type, ua_type_enum, c_loc_name)                                      \
    UA_Variant_setScalar(&c_loc_name##_variant, (ua_type*)c_loc_name, &UA_TYPES[ua_type_enum]);

static void* __OPCUA_thread_proc(void *arg) {{ 
    while(!OPCUA_stop_thread) {{
        if (OPCUA_is_disconnected) {{
            sleep(1);
            
            if((pthread_mutex_lock(&OPCUA_client_mutex)) == 0) {{ 
                UA_StatusCode retval = UA_Client_connect(client, OPCUA_uri);
                if (retval == UA_STATUSCODE_GOOD) {{
                    OPCUA_is_disconnected = 0;
                    LogInfo("OPC-UA Connected");
                }} else {{
                    OPCUA_is_disconnected = 1;
                    LogError("OPC-UA Connection failed with status code %s", UA_StatusCode_name(retval));
                }}
                pthread_mutex_unlock(&OPCUA_client_mutex);
            }}
        }} 
    }}
    return NULL;
}}

int __init_{locstr}(int argc,char **argv)
{{
    UA_StatusCode retval = UA_STATUSCODE_GOOD;
    client = UA_Client_new();
    cc = UA_Client_getConfig(client);
    char *uri = "{uri}";
    OPCUA_uri = uri;
{init}

    if(retval != UA_STATUSCODE_GOOD) {{
        LogError("OPC-UA Init Failed %d", retval);
        UA_Client_delete(client);
        return EXIT_FAILURE;
    }}
    return 0;
}}

#define READ_VALUE(ua_type, ua_type_enum, c_loc_name, ua_nodeid_type, ua_nsidx, ua_node_id)        \
    {{                                                                                            \
        if(!OPCUA_is_disconnected && pthread_mutex_trylock(&OPCUA_client_mutex) == 0) {{          \
            UA_StatusCode retval = UA_Client_readValueAttribute(                                  \
                client, ua_nodeid_type(ua_nsidx, ua_node_id), &c_loc_name##_variant);                           \
            if(retval == UA_STATUSCODE_GOOD && UA_Variant_isScalar(&c_loc_name##_variant) &&                  \
                c_loc_name##_variant.type == &UA_TYPES[ua_type_enum]) {{                                         \
                c_loc_name##_buf = *(ua_type*)c_loc_name##_variant.data;                                        \
            }}                                                                                      \
            UA_Variant_clear(&c_loc_name##_variant);                                  \
            pthread_mutex_unlock(&OPCUA_client_mutex);                                             \
        }}                                                                                          \
    }}

void __retrieve_{locstr}(void)
{{
{retrieve}
}}

#define WRITE_VALUE(ua_type, c_loc_name, ua_nodeid_type, ua_nsidx, ua_node_id)                    \
    {{                                                                                             \
        if(!OPCUA_is_disconnected && pthread_mutex_trylock(&OPCUA_client_mutex) == 0) {{           \
            UA_Client_writeValueAttribute(                                                         \
                client, ua_nodeid_type(ua_nsidx, ua_node_id), &c_loc_name##_variant);                           \
            pthread_mutex_unlock(&OPCUA_client_mutex);                                             \
        }}                                                                                          \
    }}

void __publish_{locstr}(void)
{{
{publish}
}}