/*
 * Generated by erpcgen 1.11.0 on Tue May 14 10:14:58 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "erpc_PLCObject_interface.hpp"

#if 11100 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

BeremizPLCObjectService_interface::~BeremizPLCObjectService_interface(void)
{
}
