/*
 * Generated by erpcgen 1.13.0 on Sat Nov  1 13:50:22 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "erpc_PLCObject_interface.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

BeremizPLCObjectService_interface::~BeremizPLCObjectService_interface(void)
{
}
