#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

from POULibrary import SimplePOULibraryFactory
from PLCControler import LOCATION_CONFNODE, LOCATION_VAR_MEMORY, LOCATION_VAR_OUTPUT, LOCATION_VAR_INPUT

import util.paths as paths

"""
Zephyr Native Simulation Target

Possible configurations:

1. **NonProgrammable**:
    Simulate non-programmable PLCs. No dynamic loading, no RPC.

2. **Serial**: Programmable through eRPC over Serial:
    - `Device`: The default value is `/dev/ttyUSB0`.
    - `Baudrate`: The default value is `115200`.
    Use this configuration to simulate a programmable PLC using eRPC over a serial connection.
    To connect simulation to simulation, either:
        - use 2 USB-to-Serial adapters + null modem cable.
        - launch socat to create a virtual null modem cable. For example:
            `socat pty,link=/tmp/beremiz_runtime_tty,rawer pty,link=/tmp/beremiz_IDE_tty,rawer`
            - set simulation serial-port to "/tmp/beremiz_runtime_tty"
            - set IDE serial-port to "/tmp/beremiz_IDE_tty".

3. **USB**: This configuration includes optional attributes for:
    - `VendorID`: The default value is an empty string.
    - `ProductID`: The default value is an empty string.

4. **TCP**: This configuration includes an optional attribute for:
    - `Port`: The default value is an empty string.

"""


XSD_name = "NativeSimulation"
XSD = f"""
<xsd:element name="{XSD_name}">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="SimulationType">
                <xsd:complexType>
                    <xsd:annotation><xsd:documentation>Type of simulation</xsd:documentation></xsd:annotation>
                    <xsd:choice minOccurs="0">
                        <xsd:element name="NonProgrammable">
                            <xsd:annotation><xsd:documentation>
Simulate non-programmable PLCs. No dynamic loading, no eRPC.
                            </xsd:documentation></xsd:annotation>
                        </xsd:element>
                        <xsd:element name="Serial">
                            <xsd:complexType>
                                <xsd:annotation><xsd:documentation>Serial programming</xsd:documentation></xsd:annotation>
                                <xsd:attribute name="Device" type="xsd:string" use="optional" default="/dev/ttyUSB0">
                                    <xsd:annotation><xsd:documentation>
<![CDATA[Linux serial device opened by simulation to simulate an interrupt driven UART, typically /dev/ttyUSB0
To connect simulation to simulation, either:
    - use 2 USB-to-Serial adapters + null modem cable.
    - launch socat to create a virtual null modem cable. For example:
        - run "socat pty,link=/tmp/beremiz_runtime_tty,rawer pty,link=/tmp/beremiz_IDE_tty,rawer"
        - set simulation serial-port to "/tmp/beremiz_runtime_tty"
        - set IDE serial-port to "/tmp/beremiz_IDE_tty"]]>
                                    </xsd:documentation></xsd:annotation>
                                </xsd:attribute>
                                <xsd:attribute name="Baudrate" type="xsd:integer" use="optional" default="115200"/>
                            </xsd:complexType>
                        </xsd:element>    
                        <xsd:element name="USB">
                            <xsd:complexType>
                                <xsd:attribute name="VendorID" type="xsd:string" use="optional" default=""/>
                                <xsd:attribute name="ProductID" type="xsd:string" use="optional" default=""/>
                            </xsd:complexType>
                        </xsd:element>    
                        <xsd:element name="TCP">
                            <xsd:complexType>
                                <xsd:attribute name="Port" type="xsd:integer" use="optional" default="3000"/>
                            </xsd:complexType>
                        </xsd:element>    
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>    
        </xsd:sequence>
        <xsd:attribute name="SubBoardName" type="xsd:string" use="optional" default="native/64"/>
        <xsd:attribute name="EnableGPIO" type="xsd:boolean" use="optional" default="true">
            <xsd:annotation><xsd:documentation>Enable GPIO emulation.</xsd:documentation></xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>
</xsd:element>
"""

# Pseudo CTN to generate C code an describe IOs in Location tree
class NativeSimGPIO(object):
    def CTNGenerate_C(self, buildpath, locations):
        current_location = self.GetCurrentLocation()
        locstr = "_".join(map(str, current_location))
        c_path = os.path.join(buildpath, "nativesim_gpio__%s.c" % locstr)

        c_code = f"""/*
 * Generated by beremiz/C_runtime/zephyr/native_sim/__init__.py
 */

#include "iec_types_all.h"
#include "beremiz.h"
#include "nsi_tracing.h"
#include <zephyr/drivers/gpio.h>

// Classical blinking LED (from Zephyr's native_sim.dts)
#define LED0_NODE DT_ALIAS(led0)
static const struct gpio_dt_spec led0 = GPIO_DT_SPEC_GET(LED0_NODE, gpios);

// Additional GPIOs (from gpio.overlay DTS)
#define LED1_NODE DT_NODELABEL(led1)
static const struct gpio_dt_spec led1 = GPIO_DT_SPEC_GET(LED1_NODE, gpios);

// Real data to work with
static BOOL _IX{locstr}_0_0;
static BOOL _QX{locstr}_1_0;
static LINT _ML{locstr}_2_0;
static BOOL _QX{locstr}_3_0;

// Buffers to detect changes
static BOOL _QX{locstr}_1_0_buffer;
static BOOL _QX{locstr}_3_0_buffer;

// symbols expected by PLC code
BOOL *__IX{locstr}_0_0 = &_IX{locstr}_0_0;
BOOL *__QX{locstr}_1_0 = &_QX{locstr}_1_0;
LINT *__ML{locstr}_2_0 = &_ML{locstr}_2_0;
BOOL *__QX{locstr}_3_0 = &_QX{locstr}_3_0;

void __cleanup_{locstr}(void)
{{
}}

int __init_{locstr}(int argc,char **argv)
{{
    int ret;
""" \
                 + ''.join([ f"""
	if (!gpio_is_ready_dt(&{gpiospec})) {{
		return EBUSY;
    }}
	if ((ret = gpio_pin_configure_dt(&{gpiospec}, GPIO_{state}))){{
        return ret;
    }}

""" for gpiospec, state in [
        ("led0",     "OUTPUT_ACTIVE"),
        ("led1",     "OUTPUT_ACTIVE")]]) \
                 + f"""

    // Initialization code for GPIO simulation
    // Set initial values for simulated inputs and outputs
    _IX{locstr}_0_0 = FALSE;
    _QX{locstr}_1_0 = FALSE;
    _QX{locstr}_1_0_buffer = FALSE;
    _ML{locstr}_2_0 = 0;
}}

void __retrieve_{locstr}(void)
{{
    // TODO: Read from the simulated GPIO input
    _IX{locstr}_0_0 = !_IX{locstr}_0_0;
    
    // Dumb counter
    _ML{locstr}_2_0++;
}}

void __publish_{locstr}(void)
{{
    int ret;
    if(_QX{locstr}_1_0_buffer != _QX{locstr}_1_0){{
        // Log the change in output state
        nsi_print_warning("GPIO output changed: %d\\n", _QX{locstr}_1_0);

        // Pass the new state to the simulation
        gpio_pin_set_dt(&led0,  _QX{locstr}_1_0);

        // Update the buffer to reflect the new state
        _QX{locstr}_1_0_buffer = _QX{locstr}_1_0;
    }}

    if(_QX{locstr}_3_0_buffer != _QX{locstr}_3_0){{
        // Log the change in output state
        nsi_print_warning("LED changed: %d\\n", _QX{locstr}_3_0);

        // Pass the new state to the simulation
        gpio_pin_set_dt(&led1,  _QX{locstr}_3_0);

        // Update the buffer to reflect the new state
        _QX{locstr}_3_0_buffer = _QX{locstr}_3_0;
    }}

}}
"""

        with open(c_path, 'w') as c_file:
            c_file.write(c_code)

        return [(c_path, "")], "", True
    
    def GetVariableLocationTree(self):
        current_location = self.GetCurrentLocation()
        locstr = ".".join([str(i) for i in current_location])
        entries = []
        return {"name": "Zephyr native_sim IOs",
                "type": LOCATION_CONFNODE,
                "location": locstr + ".x",
                "children": [
                    {
                        "name": "First input",
                        "type": LOCATION_VAR_INPUT,
                        "size": 1,
                        "IEC_type": "BOOL",
                        "var_name": "input_0",
                        "location": "%IX" + locstr + ".0.0",
                        "description": "Simulated input 0",
                        "children": []},
                    {
                        "name": "First output",
                        "type": LOCATION_VAR_OUTPUT,
                        "size": 1,
                        "IEC_type": "BOOL",
                        "var_name": "output_0",
                        "location": "%QX" + locstr + ".1.0",
                        "description": "Simulated output 0",
                        "children": []},
                    {
                        "name": "First counter",
                        "type": LOCATION_VAR_MEMORY,
                        "size": 64,
                        "IEC_type": "LINT",
                        "var_name": "count_0",
                        "location": "%ML" + locstr + ".2.0",
                        "description": "Simulated counter 0",
                        "children": []},
                    {
                        "name": "First LED",
                        "type": LOCATION_VAR_OUTPUT,
                        "size": 1,
                        "IEC_type": "BOOL",
                        "var_name": "output_0",
                        "location": "%QX" + locstr + ".1.0",
                        "description": "Simulated LED 0",
                        "children": []},
                ]}

def GetBuildOptions(board_cfg):
    options = []
    board_name = "native_sim"
    c_flags = []
    user_dts = []
    user_conf = []
    
    sub_board_name = board_cfg.getSubBoardName().strip()
    if sub_board_name:
        board_name += "/" + sub_board_name
    
    simulation_type = board_cfg.getSimulationType().getcontent()
    simulation_type_name = simulation_type.getLocalTag()
    programmable = simulation_type_name != "NonProgrammable"

    enable_gpio = board_cfg.getEnableGPIO()
    if enable_gpio:
        options.append("gpio")
    
    if programmable:
        options.append("programmable")
        if simulation_type_name == "Serial":
            device = simulation_type.getDevice()
            baudrate = simulation_type.getBaudrate()
            user_dts.append(f"""
                beremiz_erpc_uart {{
                    current-speed = <{baudrate}>;
                    serial-port = "{device}";
                }};
            """)
            options.append("serial")
        elif simulation_type_name == "USB":
            vendor_id = simulation_type.getVendorID()
            product_id = simulation_type.getProductID()
            
            def validate_hex_id(id_value, id_name):
                if len(id_value) != 4 or not all(c in "0123456789abcdefABCDEF" for c in id_value):
                    raise ValueError(f"Invalid {id_name}: {id_value}")

            # Validate vendor_id and product_id
            validate_hex_id(vendor_id, "VendorID")
            validate_hex_id(product_id, "ProductID")
            
            user_dts.append(f"""
                beremiz_erpc_usb {{
                    vendor-id = <0x{vendor_id}>;
                    product-id = <0x{product_id}>;
                }};
            """)
            options.append("usb")
        elif simulation_type_name == "TCP":
            port = simulation_type.getPort()
            user_dts.append(f"""
            beremiz_erpc_tcp {{
                port = <{port}>;
            }};
            """)
            options.append("tcp")
    
    libraries = [("NativeSim", SimplePOULibraryFactory(paths.AbsNeighbourFile(__file__, "pous.xml")))]
    
    IEC_channels = [(0, NativeSimGPIO)] if enable_gpio else []

    # Needed by C code included in FBs of pous.xml
    preamble = '#include "nsi_main.h"\n#include "nsi_tracing.h"\n'

    return board_name, options, c_flags, user_dts, user_conf, libraries, IEC_channels, preamble